modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Christofmeg/LandOfDrunir/issues" #optional
license="The MIT License (MIT)"
[[mods]]
modId="landofdrunir"
version="${file.jarVersion}"
displayName="Land of Drunir"
displayURL="https://github.com/Christofmeg/LandOfDrunir" #optional
logoFile="icon.png"
authors="Christofmeg"
#credits=""
description=""
[[dependencies.landofdrunir]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.landofdrunir]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[modproperties.landofdrunir]
    catalogueImageIcon="catalogue-icon.png"